nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/rancher/ui-plugin-examples/main/extensions/new-prod-reg-api/0.1.1
  compressedEndpoint: >-
    https://raw.githubusercontent.com/rancher/ui-plugin-examples/main/extensions/new-prod-reg-api/0.1.1.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.15.0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
