#!/usr/bin/env node

// Update Chart.yaml and values.yaml files

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// TODO: Should already be in the template
const UI_PLUGIN_ANNOTATION = 'uiplugin.cattle.io';

console.log('Helm file update');

if (process.argv.length !== 4) {
  console.log('Incorrect number of arguments');
  process.exit(1);
}

const pkgFolder = process.argv[2];
const destFolder = process.argv[3];

const pkgFile = JSON.parse(fs.readFileSync(path.join(pkgFolder, 'package.json'), 'utf8'));

const chartFolder = destFolder;
const chartFile = path.join(chartFolder, 'Chart.yaml');

if (!fs.existsSync(chartFolder)) {
  console.log('Charts folder does not exist');
  process.exit(1);
}

// --------------------------------------------------------------------------------
// Chart.yaml
// --------------------------------------------------------------------------------
const chart = yaml.load(fs.readFileSync(chartFile, 'utf8'));

chart.name = pkgFile.name;
chart.appVersion = pkgFile.version;
chart.version = pkgFile.version;
chart.description = pkgFile.description || `${pkgFile.name} ui plugin `;
chart.annotations[UI_PLUGIN_ANNOTATION] = 'true';

if (pkgFile.icon) {
  chart.icon = pkgFile.icon;
}

if (pkgFile.keywords) {
  chart.keywords = pkgFile.keywords;
}

if (pkgFile.homepage) {
  chart.home = pkgFile.homepage;
}

const str = yaml.dump(chart);
fs.writeFileSync(chartFile, str, 'utf8');

// --------------------------------------------------------------------------------
// values.yaml
// --------------------------------------------------------------------------------

// TODO: Change image repository in the values file
const values = {
  plugin: pkgFile.name,
};

// const valuesYaml = yaml.dump(values);
// fs.writeFileSync(path.join(chartFolder, 'values.yaml'), valuesYaml, 'utf8');

// // Create templates folder
// fs.mkdirSync(path.join(chartFolder, 'templates'), 0777);
