#!/bin/bash
cd $(dirname $0)

#Get chart directory from input
CHARTDIR=$1

#Get plugin info from package.jsonm using jq
echo "Grabbing plugin info from $2"
CHARTNAME=$(cat $2 | jq ".name" | tr -d '"')
CHARTVERSION=$(cat $2 | jq ".version" | tr -d '"')
IMAGEREPO=$3

#Edit Chart information to match plugin using yq
yq -i eval ".name = \"${CHARTNAME}\"" $CHARTDIR/Chart.yaml
yq -i eval ".version = \"${CHARTVERSION}\"" $CHARTDIR/Chart.yaml
yq -i eval ".appVersion = \"${CHARTVERSION}\"" $CHARTDIR/Chart.yaml
yq -i eval ".image.tag = \"${CHARTVERSION}\"" $CHARTDIR/values.yaml
yq -i eval ".plugin.version = \"${CHARTVERSION}\"" $CHARTDIR/values.yaml
yq -i eval ".image.repository = \"${IMAGEREPO}/${CHARTNAME}\"" $CHARTDIR/values.yaml
#yq -i eval ".global.cattle.systemDefaultRegistry = \"${IMAGEREPO}\"" $CHARTDIR/values.yaml