name: Build and Release Extension Charts

on:
  workflow_dispatch:
  release:
    types: [released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-charts:
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@plugin-examples-build-fix
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: main
      tagged_release: ${{ github.ref_name }}
      create_pr: 'true'
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
